### ISSUE TITLE
Can't use showcaseview with Fragments, getmeasurewidth\height is 0

### ISSUE THREAD

**Issue by alexkapu** [amlcurran/ShowcaseView#179]
I use the last version of ShowcaseView (v5.0)

When I tried to use it with demo app and activity it works but when I tried to use it with fragments it crashes my app

     @override
        public void onActivityCreated(Bundle savedInstanceState) {
            super.onActivityCreated(savedInstanceState);

            final ImageButton saveButton = (ImageButton) view.findViewById(R.id.button_Save);
            ViewTarget viewTarget = new ViewTarget(saveButton);

            showcaseView = new ShowcaseView.Builder(getActivity())
                    .setTarget(viewTarget)
                    .setContentTitle("Reset Button")
                    .setContentText("This will erase all the data in the table except the line that in progress")
                    .build();
        }

when I tried to do the same thing in my fragmentactivity and didn't work, but when I did the same thing but took a view that declared in the fragmentactivity and not in the fragment it worked.

the error from the logcat:

FATAL EXCEPTION: main
java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:724)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:703)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:670)
        at com.github.amlcurran.showcaseview.ShowcaseView.updateBitmap(ShowcaseView.java:169)
        at com.github.amlcurran.showcaseview.ShowcaseView.onGlobalLayout(ShowcaseView.java:343)
        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:839)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2050)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1249)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6364)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
        at android.view.Choreographer.doCallbacks(Choreographer.java:591)
        at android.view.Choreographer.doFrame(Choreographer.java:561)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
        at android.os.Handler.handleCallback(Handler.java:730)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:5419)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:525)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
        at dalvik.system.NativeStart.main(Native Method)

I understand the error but what is the cause for it?

**Comment by jernest002** [comment]
I'm  encountering this issue when trying to show the ShowcaseViews again through a context menu aciton.
