### ISSUE TITLE
java.lang.IllegalArgumentException: Layout: -998646 < 0

### ISSUE THREAD

**Issue by makovkastar** [amlcurran/ShowcaseView#182]
I've got this exception that crashed my app. Android 4.2.2, Nexus 10:

```
05-20 16:43:53.869: E/AndroidRuntime(26172): java.lang.IllegalArgumentException: Layout: -998646 < 0
05-20 16:43:53.869: E/AndroidRuntime(26172):    at android.text.Layout.<init>(Layout.java:138)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at android.text.DynamicLayout.<init>(DynamicLayout.java:99)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at android.text.DynamicLayout.<init>(DynamicLayout.java:80)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at android.text.DynamicLayout.<init>(DynamicLayout.java:63)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at android.text.DynamicLayout.<init>(DynamicLayout.java:49)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at com.github.amlcurran.showcaseview.TextDrawer.draw(TextDrawer.java:55)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at com.github.amlcurran.showcaseview.ShowcaseView.dispatchDraw(ShowcaseView.java:255)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at android.view.View.getDisplayList(View.java:12648)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at android.view.View.getDisplayList(View.java:12694)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2910)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at android.view.View.getDisplayList(View.java:12588)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at android.view.View.getDisplayList(View.java:12694)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1198)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at android.view.ViewRootImpl.draw(ViewRootImpl.java:2173)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2045)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1854)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:989)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4351)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at android.view.Choreographer.doCallbacks(Choreographer.java:562)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at android.view.Choreographer.doFrame(Choreographer.java:532)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at android.os.Handler.handleCallback(Handler.java:725)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at android.os.Handler.dispatchMessage(Handler.java:92)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at android.os.Looper.loop(Looper.java:137)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at android.app.ActivityThread.main(ActivityThread.java:5041)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at java.lang.reflect.Method.invokeNative(Native Method)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at java.lang.reflect.Method.invoke(Method.java:511)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
05-20 16:43:53.869: E/AndroidRuntime(26172):    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by viju85** [comment]
I see this issue on Nexus 6.
Can you provide the fix as a part of the library, so that others can pick it up from maven ?

**Comment by gurschitz** [comment]
+1
Happens on Nexus 10 as well, with Android 5.0.0.

**Comment by toshe** [comment]
(:+1)

Happens here as well on Nexus 10 (5.0.0). No idea why, I can't seem to reproduce it on Nexus 7.
@CollegeDev Can you please create a merge request?

**Comment by viju85** [comment]
Any update on this issue ?

**Comment by hkhc-xvpn** [comment]
Just catch this problem. It seems from my report that the problem occurs for devices with high resolution (higher than FHD). That consistent with the discussion above.

**Comment by thinkpanda** [comment]
Just catch this problem. It seems from my bug reports that the problem only occurs for devices with high resolution (larger than FHD). That consistent with the discussion above.

All of my reports about this error come from devices with 1440x2560 resolution.
