### ISSUE TITLE
Creating multiple instances of a ShowcaseView crashes the application with an outOfMemory error.

### ISSUE THREAD

**Issue by AMRoche** [amlcurran/ShowcaseView#183]
Stack Trace: 05-20 17:59:09.166  30218-30218/com.********_.**_****\* E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.OutOfMemoryError
            at android.graphics.Bitmap.nativeCreate(Native Method)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:726)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:703)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:670)
            at com.github.amlcurran.showcaseview.ShowcaseView.updateBitmap(ShowcaseView.java:202)
            at com.github.amlcurran.showcaseview.ShowcaseView.onGlobalLayout(ShowcaseView.java:370)
            at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:839)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2050)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1249)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6364)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
            at android.view.Choreographer.doCallbacks(Choreographer.java:591)
            at android.view.Choreographer.doFrame(Choreographer.java:561)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
            at android.os.Handler.handleCallback(Handler.java:730)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5419)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
            at dalvik.system.NativeStart.main(Native Method)

Steps to reproduce:
Create six separate instances of a ShowcaseView in four different views using the procedure detailed in the README.md.

Noted, this could be an application specific issue, however memory usage continually rises each time a ShowcaseView is created.

Device:
Galaxy S3 LTE, GT-I9305 running Android 4.3

**Comment by amlcurran** [comment]
@swatijet can you please post more details about how you're using
ShowcaseView?

**Comment by swatijiet** [comment]
I am using two instances of showcaseview in my 2 activities. One of my activities have 2 fragments. I am only getting error on samsung devices where the bitmap created is very big.
In my activity where i have fragments, I am making an instance of showcaseview in main activity and then using same instance in the fragments:

This is the order of call :- Fragment 1 --> Child Fragment --> to main activity. At the end of each call , i call showcaseview.hide(). This all works fine but when i move to another activity after hide() is called in main activity, I get the crash. In another activity, i have about 9 targets to show, but error comes as soon as the first target is loaded.

**Comment by amlcurran** [comment]
Hmmm I wonder if Samsung is leaking memory somewhere. I have a Samsung device at work and will try to reproduce this

**Comment by swatijiet** [comment]
@amlcurran any update on the error?
