### ISSUE TITLE
NullPointeException after hide on emulator

### ISSUE THREAD

**Issue by JanLoebel** [amlcurran/ShowcaseView#191]
Hey there,

I have a problem with ShowcaseView 5.0.0-SNAPSHOT pulled today (02.06.2014). I've created a normal FragmentActivity and added the code in the onCreated()-Method from the Wiki to highlight the HomeButton.

```
new ShowcaseView.Builder( this )
         .setTarget( new ActionViewTarget( this, ActionViewTarget.Type.HOME ) )
         .setContentTitle( "ShowcaseView" )
         .setContentText( "This is highlighting the Home button" )
         .hideOnTouchOutside()
         .build();
```

If I start it with an emulator with the following settings, start the app and click the okay button. The App will crash.
![emulator](https://cloud.githubusercontent.com/assets/1765067/3145591/6edef72a-ea39-11e3-8c47-09f21b3946d1.png)

Stacktrace:

```
06-02 09:40:09.587: E/AndroidRuntime(1993): FATAL EXCEPTION: main
06-02 09:40:09.587: E/AndroidRuntime(1993): java.lang.NullPointerException
06-02 09:40:09.587: E/AndroidRuntime(1993):     at com.github.amlcurran.showcaseview.StandardShowcaseDrawer.erase(StandardShowcaseDrawer.java:75)
06-02 09:40:09.587: E/AndroidRuntime(1993):     at com.github.amlcurran.showcaseview.ShowcaseView.dispatchDraw(ShowcaseView.java:303)
06-02 09:40:09.587: E/AndroidRuntime(1993):     at android.view.ViewGroup.drawChild(ViewGroup.java:2885)
06-02 09:40:09.587: E/AndroidRuntime(1993):     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
06-02 09:40:09.587: E/AndroidRuntime(1993):     at android.view.View.draw(View.java:10981)
06-02 09:40:09.587: E/AndroidRuntime(1993):     at android.widget.FrameLayout.draw(FrameLayout.java:450)
06-02 09:40:09.587: E/AndroidRuntime(1993):     at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2126)
06-02 09:40:09.587: E/AndroidRuntime(1993):     at android.view.ViewRootImpl.draw(ViewRootImpl.java:2026)
06-02 09:40:09.587: E/AndroidRuntime(1993):     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1634)
06-02 09:40:09.587: E/AndroidRuntime(1993):     at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2442)
06-02 09:40:09.587: E/AndroidRuntime(1993):     at android.os.Handler.dispatchMessage(Handler.java:99)
06-02 09:40:09.587: E/AndroidRuntime(1993):     at android.os.Looper.loop(Looper.java:137)
06-02 09:40:09.587: E/AndroidRuntime(1993):     at android.app.ActivityThread.main(ActivityThread.java:4424)
06-02 09:40:09.587: E/AndroidRuntime(1993):     at java.lang.reflect.Method.invokeNative(Native Method)
06-02 09:40:09.587: E/AndroidRuntime(1993):     at java.lang.reflect.Method.invoke(Method.java:511)
06-02 09:40:09.587: E/AndroidRuntime(1993):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
06-02 09:40:09.587: E/AndroidRuntime(1993):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
06-02 09:40:09.587: E/AndroidRuntime(1993):     at dalvik.system.NativeStart.main(Native Method)
```

I added some logs into the source code here is the result:

```
06-02 09:25:29.263: E/this(1807): updateBitmap() bitmapBuffer: android.graphics.Bitmap@91076528
06-02 09:25:29.263: E/this(1807): updateBitmap() bitmapBuffer: android.graphics.Bitmap@91076528
06-02 09:25:29.273: E/this(1807): updateBitmap() bitmapBuffer: android.graphics.Bitmap@91076528
06-02 09:25:29.283: E/this(1807): dispatchDraw() bitmapBuffer: android.graphics.Bitmap@91076528
06-02 09:25:29.283: E/this(1807): bitmapBuffer: android.graphics.Bitmap@91076528 - this: com.github.amlcurran.showcaseview.StandardShowcaseDrawer@90b31f48
06-02 09:25:29.373: E/this(1807): dispatchDraw() bitmapBuffer: android.graphics.Bitmap@91076528
06-02 09:25:29.383: E/this(1807): bitmapBuffer: android.graphics.Bitmap@91076528 - this: com.github.amlcurran.showcaseview.StandardShowcaseDrawer@90b31f48
06-02 09:25:29.403: E/this(1807): updateBitmap() bitmapBuffer: android.graphics.Bitmap@91076528
06-02 09:25:29.463: E/this(1807): dispatchDraw() bitmapBuffer: android.graphics.Bitmap@91076528
06-02 09:25:29.463: E/this(1807): bitmapBuffer: android.graphics.Bitmap@91076528 - this: com.github.amlcurran.showcaseview.StandardShowcaseDrawer@90b31f48
06-02 09:25:29.523: E/this(1807): dispatchDraw() bitmapBuffer: android.graphics.Bitmap@91076528
06-02 09:25:29.523: E/this(1807): bitmapBuffer: android.graphics.Bitmap@91076528 - this: com.github.amlcurran.showcaseview.StandardShowcaseDrawer@90b31f48

<clicked the okay button>

06-02 09:25:30.223: E/this(1807): onClick() bitmapBuffer: android.graphics.Bitmap@91076528
06-02 09:25:30.223: E/this(1807): hide() bitmapBuffer: android.graphics.Bitmap@91076528
06-02 09:25:30.223: E/this(1807): clearBitmap() bitmapBuffer: android.graphics.Bitmap@91076528
06-02 09:25:30.223: E/this(1807): dispatchDraw() bitmapBuffer: null
06-02 09:25:30.223: E/this(1807): bitmapBuffer: null - this: com.github.amlcurran.showcaseview.StandardShowcaseDrawer@90b31f48
```

I dont't know why android try to dispatch draw after the view was hide (bitmapBuffer cleared). When I activate the "Use Host GPU" in the Emulator settings I couldn't reprodruce this exception. Any ideas?

**Comment by jhartwig** [comment]
Hi,

not working for me, or am I doing something wrong?
compile 'com.github.amlcurran.showcaseview:library:5.1.0-SNAPSHOT'

Cheers
