### ISSUE TITLE
java.lang.IllegalArgumentException: width and height must be > 0

### ISSUE THREAD

**Issue by alex-dokienko** [amlcurran/ShowcaseView#197]
java.lang.IllegalArgumentException: width and height must be > 0
at android.graphics.Bitmap.createBitmap(Bitmap.java:603)
at android.graphics.Bitmap.createBitmap(Bitmap.java:585)
at com.github.amlcurran.showcaseview.ShowcaseView.updateBitmap(ShowcaseView.java:169)
at com.github.amlcurran.showcaseview.ShowcaseView.access$100(ShowcaseView.java:29)
at com.github.amlcurran.showcaseview.ShowcaseView$1.run(ShowcaseView.java:148)
at android.os.Handler.handleCallback(Handler.java:605)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4517)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:993)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:760)
at dalvik.system.NativeStart.main(Native Method)

**Comment by igorregis** [comment]
@amlcurran Sorry to post on a closed task but I am using ShowcaseView 5.4.0 and I'm getting a quite similar error, as you can see by the Stack below. Sadly I can't catch it since it's out of my stack. I have noticed that it seems to happen when I switch between screens too rapidly and looks like there's not enough time to show the showcaseview.

`Fatal Exception: java.lang.IllegalArgumentException: width and height must be > 0
       at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:787)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:754)
       at com.github.amlcurran.showcaseview.ShowcaseView.updateBitmap(ShowcaseView.java:211)
       at com.github.amlcurran.showcaseview.ShowcaseView.access$100(ShowcaseView.java:51)
       at com.github.amlcurran.showcaseview.ShowcaseView$1.run(ShowcaseView.java:187)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5146)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
       at dalvik.system.NativeStart.main(NativeStart.java)`

**Comment by amlcurran** [comment]
Yup, this seems to be an issue still, I'll reopen this one!

**Comment by barbeau** [comment]
For us, it appears that this is fixed in 'com.github.amlcurran.showcaseview:library:5.4.3'`, released yesterday.

Could someone else try updating to the newest library version to confirm?

**Comment by igorregis** [comment]
I will update to this version and report back

**Comment by igorregis** [comment]
It looks like is fixed now. I haven't received any crash report by the past month

**Comment by amlcurran** [comment]
Great!

**Comment by igorregis** [comment]
Bad news. The error comeout again:
```
Fatal Exception: java.lang.IllegalArgumentException: width and height must be > 0
       at android.graphics.Bitmap.createBitmap(Bitmap.java:855)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:834)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:801)
       at com.github.amlcurran.showcaseview.s.i(ShowcaseView.java:211)
       at com.github.amlcurran.showcaseview.s.b(ShowcaseView.java:51)
       at com.github.amlcurran.showcaseview.s$1.run(ShowcaseView.java:187)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

I received the report from Crashlytics into a Motorola XT1068 with 37% of free RAM.

The user reported that he was performing a switch between screens, and he was faster that the app. He switched before the app show the ShowcaseView

That happened on the same version I had applied the fix above
