### ISSUE TITLE
Not working with Android L / Material design

### ISSUE THREAD

**Issue by yanniks** [amlcurran/ShowcaseView#203]
When I started modifying my app for Android L, I noticed that the app crashes when ShowcaseView gets initialized:

    java.lang.RuntimeException: insertShowcaseViewWithType cannot be used when the theme has no ActionBar
            at com.github.amlcurran.showcaseview.targets.ActionBarReflector.getHomeButton(ActionBarReflector.java:27)
            at com.github.amlcurran.showcaseview.targets.ActionBarReflector.getActionBarView(ActionBarReflector.java:20)
            at com.github.amlcurran.showcaseview.targets.ActionViewTarget.setUp(ActionViewTarget.java:22)
            at com.github.amlcurran.showcaseview.targets.ActionViewTarget.getPoint(ActionViewTarget.java:29)
            at com.github.amlcurran.showcaseview.ShowcaseView$1.run(ShowcaseView.java:149)
            at android.os.Handler.handleCallback(Handler.java:738)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5070)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:836)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:631)

**Comment by avizana** [comment]
hi, I tried to use showcaseview with Material design with no luck. can someone post a working example of how to use it with Material design (I didn't understand the wrapper suggestion)?

Thanks in advance

**Comment by leonardoliv** [comment]
i made this working by doing the following:
        
                        ShowcaseView.Builder showCaseBuilder = new ShowcaseView.Builder(this);

                        showCaseBuilder.setTarget(new ViewTarget(((Toolbar) findViewById(R.id.action_bar)).getChildAt(0)));
                        showCaseBuilder.setContentTitle(R.string.welcome);
                        showCaseBuilder.setContentText(R.string.showcase_msg);
      
                        showCaseBuilder.build();

**Comment by AlexGilleran** [comment]
@leonardoliv  works for me too, lifesaver!

**Comment by rcketscientist** [comment]
Spent the afternoon developing action bar workarounds for Material, figured I'd share:

    private void setTutorialHomeView(boolean animate)
    {
        PointTarget home = new PointTarget(16,16);  //Design guideline is 32x32
        tutorial.setShowcase(home, animate);
    }

    /**
     * Showcase item or overflow if it doesn't exist
     * @param itemId menu id
     * @param animate Animate the showcase from the previous spot.  Recommend FALSE if previous showcase was NONE
     */
    private void setTutorialActionView(int itemId, boolean animate)
    {
		ViewTarget target;
		View itemView = findViewById(itemId);
		if (itemView == null)
		{
			//List of all mToolbar items, assuming last is overflow
			List<View> views = mToolbar.getTouchables();
			target = new ViewTarget(views.get(views.size()-1)); //overflow
		}
		else
		{
			target = new ViewTarget(itemView);
		}

		tutorial.setShowcase(target, animate);
    }

For a nav spiner, for example, if you add it to the toolbar with an id the above will still work.  The only thing I'm not sure how to allocate is the share button.  If anyone has any ideas for that let me know.

**Comment by blundell** [comment]
:+1:

**Comment by Burtan** [comment]
Has anyone successfully find a workaround for NavigationView menu itmes?

**Comment by amlcurran** [comment]
@Burtan didn't realise that was an issue, could you please raise a separate issue?
