### ISSUE TITLE
NPE API Level 14 when dismissing SCV

### ISSUE THREAD

**Issue by IamJackppot** [amlcurran/ShowcaseView#239]
I get the following error when trying to dismiss the SCV on API level 14. 

I get the following error once OK is pressed:

     FATAL EXCEPTION: main
    java.lang.NullPointerException
 	at com.github.amlcurran.showcaseview.StandardShowcaseDrawer.erase(StandardShowcaseDrawer.java:91)
 	at com.github.amlcurran.showcaseview.ShowcaseView.dispatchDraw(ShowcaseView.java:265)
 	at android.view.ViewGroup.drawChild(ViewGroup.java:2897)
 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2495)
 	at android.view.View.draw(View.java:10883)
 	at android.widget.FrameLayout.draw(FrameLayout.java:450)
 	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2106)
 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2005)
 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1613)
 	at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2418)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:4340)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:511)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
 	at dalvik.system.NativeStart.main(Native Method)

**Comment by jamchamb** [comment]
+1. Can a fixed version be uploaded to Maven?
