### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getLocationInWindow(int[])' on a null object reference

### ISSUE THREAD

**Issue by PetoU** [amlcurran/ShowcaseView#260]
when trying to set target to other view (imageview) than ActionViewTarget.Type:

```
.setTarget(new ActionItemTarget(getActivity(), R.id.taken_photo))
```

I got :

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getLocationInWindow(int[])' on a null object reference
            at com.github.amlcurran.showcaseview.targets.ViewTarget.getPoint(ViewTarget.java:25)
            at com.github.amlcurran.showcaseview.targets.ActionItemTarget.getPoint(ActionItemTarget.java:28)
            at com.github.amlcurran.showcaseview.ShowcaseView$1.run(ShowcaseView.java:149)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by Saudasadaf** [comment]
I get the following error when I'm trying to access some item in action bar.
Can you please help how can i add showcase on action bar item.
My action bar  contain 4 items

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getLocationInWindow(int[])' on a null object reference
                                                     at com.snapdeal.seller.catalog.fragments.CatalogFragment$4.getPoint(CatalogFragment.java:411)
                                                     at com.github.amlcurran.showcaseview.ShowcaseView$1.run(ShowcaseView.java:188)
                                                     at android.os.Handler.handleCallback(Handler.java:746)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by amlcurran** [comment]
@Saudasadaf you get that if the view is not visible. If you're still coming across your issue can you please raise a new Github issue, as this one is closed?
