### ISSUE TITLE
Target home button ( nagivation drawer icon on top left of toolbar)

### ISSUE THREAD

**Issue by tryadelion** [amlcurran/ShowcaseView#334]
Hello, i'm currently trying to target the android.R.home to highlight the navigation drawer launch icon, but the library throws a null pointer exception. is there any special behaviour i should bear in mind when using items from Toolbar (support lib)?

**Comment by amlcurran** [comment]
No, this is probably a bug on my part - I'l take a look soon!

**Comment by tryadelion** [comment]
ooh okay. will provide a stacktrace as soon as i can.

**Comment by MahmoudB** [comment]
Having the same trouble here.

**Comment by djdance** [comment]
too. says no actionbar, but actually its present

**Comment by sandro-csimas** [comment]
The same here!

**Comment by DropArtDev** [comment]
I am doing it like this:
```
new ShowcaseView.Builder(this)
                        .withMaterialShowcase()
                        .setTarget(new ViewTarget(android.R.id.home, this))
                        .setContentTitle("...")
                        .setContentText("...")
                        .setStyle(...)
                        .singleShot(...)
                        .build();
```

And I am getting this error:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getLocationInWindow(int[])' on a null object reference
                                                                          at com.github.amlcurran.showcaseview.targets.ViewTarget.getPoint(ViewTarget.java:41)
                                                                          at com.github.amlcurran.showcaseview.ShowcaseView$1.run(ShowcaseView.java:191)
                                                                          at android.os.Handler.handleCallback(Handler.java:815)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                          at android.os.Looper.loop(Looper.java:194)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
```
Please fix it as fast as possible. Thank you!

**Comment by tryadelion** [comment]
seems like i'm not the only one. @amlcurran

**Comment by sirkalmi** [comment]
+1

**Comment by amlcurran** [comment]
So I've had a look at this. Yet again, this is a limitation in AppCompat, as it no longer allows us to access the view.

You can use reflection to access the view, which may break between versions of the AppCompat library. This is how to access the view using reflection:

```java
Field field = Toolbar.class.getDeclaredField("mNavButtonView");
field.setAccessible(true);
View navigationView = (View) field.get(toolbar);
ViewTarget target = new ViewTarget(navigationView);
```

**Comment by amlcurran** [comment]
I've added a ViewTarget that you can copy into your own project to use. This should work with AppCompat 23.X.0, but I'm not sure how will it will work with other versions.

Hope that helps!

https://github.com/amlcurran/ShowcaseView/blob/master/sample/src/main/java/com/github/amlcurran/showcaseview/sample/ViewTargets.java
