### ISSUE TITLE
Sample does not contain Fragments demo

### ISSUE THREAD

**Issue by sidsverma** [amlcurran/ShowcaseView#336]
I couldn't find the code where it is used with fragments. I saw it in the demo app but couldn't spot the code.

**Comment by amlcurran** [comment]
Whoops I think I've removed that sample! 

Using Fragments is very easy though, just be sure to create the `ShowcaseView` in or after `Fragment.onActivityCreated()`

**Comment by sidsverma** [comment]
Ok, got it. Thanks :)

**Comment by Scarfoo** [comment]
I am creating it in Fragment#onActivityCreated() and still getting this issue (however, seems that only on android < 5)

java.lang.IllegalArgumentException: width and height must be > 0
at android.graphics.Bitmap.createBitmap(Bitmap.java:638)
at android.graphics.Bitmap.createBitmap(Bitmap.java:620)
at com.github.amlcurran.showcaseview.ShowcaseView.updateBitmap(ShowcaseView.java:199)
at com.github.amlcurran.showcaseview.ShowcaseView.access$300(ShowcaseView.java:47)
at com.github.amlcurran.showcaseview.ShowcaseView$UpdateOnGlobalLayout.onGlobalLayout(ShowcaseView.java:797)
at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:646)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1730)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1004)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4218)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
at android.view.Choreographer.doCallbacks(Choreographer.java:555)
at android.view.Choreographer.doFrame(Choreographer.java:525)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4745)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
at dalvik.system.NativeStart.main(Native Method)
