### ISSUE TITLE
OutOfMemoryError when re-displaying ShowcaseViews

### ISSUE THREAD

**Issue by dev-JE02** [amlcurran/ShowcaseView#342]
I have a feature wherein the user can see the tutorial again if he wants. So I tried re-launching the 9 ShowcaseView tutorial for 3 times and it crashes before finishing the third one.

java.lang.OutOfMemoryError: Failed to allocate a 7672332 byte allocation with 7471984 free bytes and 7MB until OOM
at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
at android.graphics.Bitmap.nativeCreate(Native Method)
at android.graphics.Bitmap.createBitmap(Bitmap.java:817)
at android.graphics.Bitmap.createBitmap(Bitmap.java:794)
at android.graphics.Bitmap.createBitmap(Bitmap.java:761)
at com.github.amlcurran.showcaseview.ShowcaseView.updateBitmap(ShowcaseView.java:199)
at com.github.amlcurran.showcaseview.ShowcaseView.access$300(ShowcaseView.java:47)
at com.github.amlcurran.showcaseview.ShowcaseView$UpdateOnGlobalLayout.onGlobalLayout(ShowcaseView.java:797)
at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:815)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1897)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1078)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5875)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
at android.view.Choreographer.doCallbacks(Choreographer.java:580)
at android.view.Choreographer.doFrame(Choreographer.java:550)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5349)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by dev-JE02** [comment]
I'm  using v5.3.0  btw

**Comment by dev-JE02** [comment]
It was my fault for not going over the other issues first

**Comment by amlcurran** [comment]
:+1: you should find this fixed in 5.4.0

**Comment by dev-JE02** [comment]
Yes thanks, and also please update the README for the latest version. I also took a look at it to see if I was using the latest version. You've made an awesome library!

**Comment by amlcurran** [comment]
Will do! Hoping to automate the readme so well have fewer mistakes like
this in the future. Thanks for pointing it out!
