### ISSUE TITLE
Error inflating class com.github.amlcurran.showcaseview.ShowcaseView

### ISSUE THREAD

**Issue by dev-JE02** [amlcurran/ShowcaseView#346]
I am trying to make a ShowcaseManager that would manage multiple instances of showcaseViews. But the problem is I can't seem to inflate a showcaseView and get this error : 
```
Caused by: java.lang.NoSuchMethodException: <init> [class android.content.Context, interface android.util.AttributeSet]
 at java.lang.Class.getConstructor(Class.java:531)
 at java.lang.Class.getConstructor(Class.java:495)
 at android.view.LayoutInflater.createView(LayoutInflater.java:580)
 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
 at android.view.LayoutInflater.inflate(LayoutInflater.java:482) 
 at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
 at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
 at [package].utils.tutorial.ShowcaseManager.newInstanceOfShowcaseView(ShowcaseManager.java:57) 
 at [package].utils.tutorial.ShowcaseManager.addView(ShowcaseManager.java:47) 
 at [package].screens.fragments.presentors.PostPresentor.showTutorial(PostPresentor.java:721) 
 at [package].screens.fragments.presentors.PostPresentor.showOnlinePostScreenTutorial(PostPresentor.java:259) 
 at [package].screens.fragments.presentors.PostPresentor.OnRequestSuccess(PostPresentor.java:588) 
 at [package].framework.APIRequestsManager.sendSuccessResponse(APIRequestsManager.java:649) 
 at [package].framework.APIRequestsManager.access$000(APIRequestsManager.java:40) 
 at [package].framework.APIRequestsManager$10.onResponse(APIRequestsManager.java:301) 
 at [package].framework.JsonNodeRequest.deliverResponse(JsonNodeRequest.java:157) 
 at [package].framework.JsonNodeRequest.deliverResponse(JsonNodeRequest.java:27) 
 at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99) 
 at android.os.Handler.handleCallback(Handler.java:739) 
 at android.os.Handler.dispatchMessage(Handler.java:95) 
 at android.os.Looper.loop(Looper.java:135) 
 at android.app.ActivityThread.main(ActivityThread.java:5221) 
 at java.lang.reflect.Method.invoke(Native Method) 
 at java.lang.reflect.Method.invoke(Method.java:372)
```
Looks like it is looking for an implementation of a constructor. Is there a way around this with the current library version? Or can you suggest a better way to show consecutive ShowcaseViews aside from adding OnShowcaseEventListeners on every one of them?

**Comment by amlcurran** [comment]
Unfortunately, ShowcaseView doesn't support being inflated from XML, which it looks like what you're doing at the moment. 

Unfortunately, the best way of showing multiple showcases is like you mentioned, using listeners. I've added an issue #347, if you'd like to track the implementation/provide input
