### ISSUE TITLE
NullPointerException in Galaxy S2 (GT-I9100P) with Android 4.0.3 - 4.0.4

### ISSUE THREAD

**Issue by dperalesferrera** [amlcurran/ShowcaseView#384]
Run perfectly with all the devices I tested but Galaxy S2 (GT-I9100P) Android 4.0.3 - 4.0.4 give a NullPointerException. Target version is min HONEYCOMB and I am using 5.4.1 latest version

```
java.lang.NullPointerException
	at android.animation.PropertyValuesHolder.setupSetterAndGetter(PropertyValuesHolder.java:513)
	at android.animation.ObjectAnimator.initAnimation(ObjectAnimator.java:392)
	at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:544)
	at android.animation.ValueAnimator.start(ValueAnimator.java:934)
	at android.animation.ValueAnimator.start(ValueAnimator.java:957)
	at android.animation.ObjectAnimator.start(ObjectAnimator.java:370)
	at android.animation.AnimatorSet.start(AnimatorSet.java:507)
	at com.github.amlcurran.showcaseview.AnimatorAnimationFactory.animateTargetToPoint(AnimatorAnimationFactory.java:77)
	at com.github.amlcurran.showcaseview.ShowcaseView$1.run(ShowcaseView.java:195)
	at android.os.Handler.handleCallback(Handler.java:605)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4511)
	at java.lang.reflect.Method.invokeNative(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:980)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:747)
	at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by IvanAldrich** [comment]
hi, i got the same exception this days, have you got a solution for this?
