### ISSUE TITLE
OutOfMemory

### ISSUE THREAD

**Issue by mgursch** [amlcurran/ShowcaseView#392]
Hello

I see following stacktrace in crashlogs:

Fatal Exception: java.lang.OutOfMemoryError
       at android.graphics.BitmapFactory.nativeDecodeAsset(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:521)
       at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:374)
       at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:785)
       at android.content.res.Resources.loadDrawable(Resources.java:2005)
       at android.content.res.Resources.getDrawable(Resources.java:673)
       at android.support.v4.content.res.ResourcesCompat.getDrawable(ResourcesCompat.java:62)
       at com.github.amlcurran.showcaseview.StandardShowcaseDrawer.<init>(StandardShowcaseDrawer.java:45)
       at com.github.amlcurran.showcaseview.ShowcaseView.<init>(ShowcaseView.java:127)
       at com.github.amlcurran.showcaseview.ShowcaseView.<init>(ShowcaseView.java:99)
       at com.github.amlcurran.showcaseview.ShowcaseView$Builder.<init>(ShowcaseView.java:453)
       at com.github.amlcurran.showcaseview.ShowcaseView$Builder.<init>(ShowcaseView.java:442)
       at com.landwirt.gui.all.custom.showcase.ShowcaseManager.showSearchShowCase(ShowcaseManager.java:26)
       at com.landwirt.gui.start.activities.MainNavigationDrawerActivity.showSearchShowcase(MainNavigationDrawerActivity.java:817)
       at com.landwirt.gui.classifieds.fragments.ClassifiedsListFragment.setup(ClassifiedsListFragment.java:496)
       at com.landwirt.gui.classifieds.fragments.ClassifiedsListFragment.onCreateView(ClassifiedsListFragment.java:400)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
       at android.os.Handler.handleCallback(Handler.java:725)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:153)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)

any ideas to prevent this? I only show just one single showcase but i get "a lot" exceptions. 

thanks a lot

**Comment by amlcurran** [comment]
Which version of the library are you using? And on which devices do these crashes happen?

**Comment by mgursch** [comment]
Hi

Im using versoin 5.4.3.

most crashes on samsung devices

top crash device: samsung sm_g388f52
other devices: gt_i9060i8, gt_i90605, Wiko lenny84, Wiko highway signs8, ...

**Comment by mgursch** [comment]
Is there any progress on this?

Still getting a lot of crashes

**Comment by javadVatan** [comment]
try it:  multiDexEnabled=true  on  build.gradle(Modoul app)  in defaultConfig {"write here"}

**Comment by fadeltd** [comment]
Hi

I'm having this problem too,
I'm using version 5.4.3

top crash device  Samsung Galaxy Note2 (t0lteskt), 2048MB RAM, Android 4.4
at com.github.amlcurran.showcaseview.ShowcaseView.updateBitmap (ShowcaseView.java:214)

I think this is because of this line

bitmapBuffer = Bitmap.createBitmap(getMeasuredWidth(), getMeasuredHeight(), Bitmap.Config.ARGB_8888);
