### ISSUE TITLE
RuntimeException on insertShowcaseViewWithType

### ISSUE THREAD

**Issue by shilu-stha** [amlcurran/ShowcaseView#442]
I get this error on adding the view.
`FATAL EXCEPTION: main
                                                                         Process: com.amage.chitooo.debug, PID: 29456
                                                                         java.lang.RuntimeException: insertShowcaseViewWithType cannot be used when the theme has no ActionBar
                                                                             at com.github.amlcurran.showcaseview.targets.ActionBarReflector.getHomeButton(ActionBarReflector.java:43)
                                                                             at com.github.amlcurran.showcaseview.targets.ActionBarReflector.getActionBarView(ActionBarReflector.java:36)
                                                                             at com.github.amlcurran.showcaseview.targets.ActionViewTarget.setUp(ActionViewTarget.java:38)
                                                                             at com.github.amlcurran.showcaseview.targets.ActionViewTarget.getPoint(ActionViewTarget.java:45)
                                                                             at com.github.amlcurran.showcaseview.ShowcaseView$1.run(ShowcaseView.java:191)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by mhasanzadehir** [comment]
I get it ,too.

**Comment by prasad456** [comment]
I too have same issue
@mahdihs76  have you used any other library?
