### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getLocationInWindow(int[])' on a null object reference

### ISSUE THREAD

**Issue by developer1011** [amlcurran/ShowcaseView#454]
Getting a NPE in version com.github.amlcurran.showcaseview:library:5.4.3

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getLocationInWindow(int[])' on a null object reference
at com.github.amlcurran.showcaseview.targets.ViewTarget.getPoint(ViewTarget.java:41)
at com.github.amlcurran.showcaseview.ShowcaseView$1.run(ShowcaseView.java:191)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:155)
at android.app.ActivityThread.main(ActivityThread.java:5696)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

```

**Comment by barsysindia** [comment]
Even i am facing the same exception when trying to put showcase view above an alert dialog.
