### ISSUE TITLE
Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 8 to color: type=0x1

### ISSUE THREAD

**Issue by masterchop** [amlcurran/ShowcaseView#463]
I cant execute it anymore it complains about errors do you know what could cause this?

04-16 00:40:21.946 9105-9105/com.blogspot.choplabalagun.bluetoothcarbff D/AndroidRuntime: Shutting down VM
04-16 00:40:21.949 9105-9105/com.blogspot.choplabalagun.bluetoothcarbff E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.blogspot.choplabalagun.bluetoothcarbff, PID: 9105
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at android.view.View$DeclaredOnClickListener.onClick(View.java:5362)
        at android.view.View.performClick(View.java:6303)
        at android.widget.CompoundButton.performClick(CompoundButton.java:134)
        at android.view.View$PerformClick.run(View.java:24828)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at android.view.View$DeclaredOnClickListener.onClick(View.java:5357)
        at android.view.View.performClick(View.java:6303) 
        at android.widget.CompoundButton.performClick(CompoundButton.java:134) 
        at android.view.View$PerformClick.run(View.java:24828) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6798) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
     Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 8 to color: type=0x1
        at android.content.res.TypedArray.getColor(TypedArray.java:473)
        at com.github.amlcurran.showcaseview.ShowcaseView.updateStyle(ShowcaseView.java:549)
        at com.github.amlcurran.showcaseview.ShowcaseView.<init>(ShowcaseView.java:94)
        at com.github.amlcurran.showcaseview.ShowcaseView.<init>(ShowcaseView.java:62)
        at com.github.amlcurran.showcaseview.ShowcaseView$Builder.<init>(ShowcaseView.java:378)
        at com.blogspot.choplabalagun.bluetoothcarbff.classes.Help.CustomHelp(Help.java:62)
        at com.blogspot.choplabalagun.bluetoothcarbff.MainActivity.CheckBoxClick(MainActivity.java:420)
        at java.lang.reflect.Method.invoke(Native Method) 
        at android.view.View$DeclaredOnClickListener.onClick(View.java:5357) 
        at android.view.View.performClick(View.java:6303) 
        at android.widget.CompoundButton.performClick(CompoundButton.java:134) 
        at android.view.View$PerformClick.run(View.java:24828) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6798) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by masterchop** [comment]
Fixed by updating to latest version:

compile 'com.github.amlcurran.showcaseview:library:5.4.3'

and make sure the listener contained:

   @Override
                    public void onShowcaseViewTouchBlocked(MotionEvent motionEvent) {

                    }
